### ISSUE TITLE
Newline showing up as missing character

### ISSUE THREAD

**Issue by lunabunn** [mooman219/fontdue#117]
Using the layout API, newlines are showing up as missing characters with some fonts:
![unknown](https://user-images.githubusercontent.com/29861658/171987899-c0ecc214-b943-4c8f-bc1b-c678d3de8b4a.png)
Is the user code expected to special-case `\n` when rendering?

A couple of fonts with this issue:
- [neodgm](https://github.com/Dalgona/neodgm/releases/download/v1.530/neodgm.ttf)
- [monogram](https://datagoblin.itch.io/monogram)

**Comment by lunabunn** [comment]
"Fixed" by checking `CharacterData::rasterize()` before rendering a given glyph. Is this the intended way to handle this?

**Comment by mooman219** [comment]
Yes that's intentional. Layout produces the position of all characters you pass in, and it's up to you on if you want to render. I added `CharacterData::rasterize()` as an easier method to test if you want to render that glyph in the general case. Some fonts have glpyh data for whitespace like new lines and spaces that you may want to display.
