### ISSUE TITLE
Characters not rendered at size == scale can be "off" by a pixel

### ISSUE THREAD

**Issue by aclysma** [mooman219/fontdue#60]
I have in-engine text rendering working. For now I hardcode scale == 40.0. I noticed when I render font size at 40px it looks great, but this other text at 15px has the appearance of character spacing/alignment being off by a pixel.

![image](https://user-images.githubusercontent.com/316070/109522740-7187ac80-7a63-11eb-8f5d-c6fe36c7335f.png)

1) There's a good chance that this is expected behavior, but if you know for certain it is/isn't, would appreciate it! I have tried mipmapping the font texture but it did not improve it.
2) I would consider rasterizing the font at two different scales to solve this, but some fonts have many characters and makes creating a new "copy" of the font at a different scale very expensive, even if I'm only going to rasterize a few of them. (mentioned in #59). Would you be interested in a pull request to add a way to filter what characters to load?

Thanks for the great library!

**Comment by mooman219** [comment]
Have you tried switching your CoordinateSystem?

**Comment by aclysma** [comment]
I think I did but it was long enough ago that I don’t recall exactly what happened. I can try it again

**Comment by mooman219** [comment]
I recognize the positioning error, it happens when you tell Fontdue the wrong coordinate system. It needs to know if Y+ is up relative to the monitor or Y+ is down relative to the monitor. If you get a chance, if you're calling `let mut layout = Layout::new(CoordinateSystem::PositiveYUp);` anywhere, try using `CoordinateSystem::PositiveYDown` (or vice versa). If you're still having an issue please re-open this bug or make a new one.
