### ISSUE TITLE
Doc: what does "scale" do?

### ISSUE THREAD

**Issue by dhardy** [mooman219/fontdue#68]
As far as I can tell from reading the code, this is a simplification step (performed while loading a font) which omits details which would not be visible at smaller sizes. Is that correct?

Related: #60.

Also related: #49. If I wished to render a glyph for multiple sub-pixel positions (e.g. `(0, 0)` and `(0.5, 0)` — *not* RGB sub-pixel rendering)... this isn't supported. Does the "outline simplification" above conflict with supporting this?

**Comment by mooman219** [comment]
> As far as I can tell from reading the code, this is a simplification step (performed while loading a font) which omits details which would not be visible at smaller sizes. Is that correct?

Yes

https://docs.rs/fontdue/0.5.0/fontdue/struct.FontSettings.html#structfield.scale

---

> Related: #60.

?

https://docs.rs/fontdue/0.5.0/fontdue/layout/struct.Layout.html#method.new

---

> Also related: #49. If I wished to render a glyph for multiple sub-pixel positions (e.g. (0, 0) and (0.5, 0) — not RGB sub-pixel rendering)... this isn't supported. Does the "outline simplification" above conflict with supporting this?

Outline simplification is independent from rasterization. Sub-pixel positioning as described is trivial.

![image](https://user-images.githubusercontent.com/865769/116373834-94fc7880-a7c2-11eb-8fff-82afdb811d97.png)

This already works in `fontdue` but [I didn't expose it](https://github.com/mooman219/fontdue/blob/master/src/font.rs#L481) (see: offset_x/offset_y). I'll expose it when I do a pass at cleaning up layout since it'll break everyone with an extra parameter and it has caching implications.
