### ISSUE TITLE
Please use the Zlib license <3 <3 <3

### ISSUE THREAD

**Issue by Lokathor** [mooman219/fontdue#7]
It's better for the long term health of the Rust ecosystem.

You don't need to _remove_ the MIT license though! You could simply add Zlib as an option

```toml
license = "MIT OR Zlib"
```

**Comment by weswigham** [comment]
https://github.com/apple/swift/pull/17

**Comment by solarane** [comment]
@mooman219 What is your stance on this change?

Was this change to be made, ever, now would be the perfect time with only 4 contributors to the project.

> It's better for the long term health of the Rust ecosystem.

IMHO, zlib is just an all-around better alternative to MIT. Instead of forcing the burden of including license text on its users (which is just more to think about, and doesn't mean much considering this license text could be hidden literally *anywhere*), it *encourages* attribution in a nice, open-source, permissive manner; though, as Lokathor said, you should leave the MIT as an option either way, for compatibility with the Rust stdlib.

I think this issue should be given some thought and, if you are not a fan of the idea, be closed. Each time I come to this repo and see this issue still open, I'm filled with hope. Yet, the crate is still licensed under MIT, with no apparent moves being made toward the *superior license*. (┰⌒┰)

**Comment by mooman219** [comment]
it's hard to switch D:

**Comment by Lokathor** [comment]
Just add it as a PR and get all previous contribution people who touched code to sign off on it

**Comment by mooman219** [comment]
I cannot switch licenses for legal reasons right now.
