### ISSUE TITLE
Slow parsing of malformed font files

### ISSUE THREAD

**Issue by 5225225** [mooman219/fontdue#97]
Fuzz target:

```rust
#![no_main]
use libfuzzer_sys::fuzz_target;

fuzz_target!(|data: &[u8]| {
    fontdue::Font::from_bytes(data, Default::default());
});
```

Samples are in a zip file to stop github complaining about the file type

155 seconds: [slow.zip](https://github.com/mooman219/fontdue/files/7798366/slow.zip)
33 seconds: [slow.zip](https://github.com/mooman219/fontdue/files/7798367/slow.zip)

**Comment by mooman219** [comment]
Very neat. I'm not sure if I can reasonably defend against this, but I'll look into this.

**Comment by Rush** [comment]
I think this is critical for any applications where users can provide their own font files.

**Comment by mooman219** [comment]
The two sample fonts specifically:

Both trigger a Result::err() immediately for me right now for being too malformed. So this is fixed.


The DoS issue in general:

I do not recommend using `fontdue` for untrusted input because it can be used to take an unreasonable amount of time. The user won't be able to trigger any unsafe behavior, but it can be used to lockup compute resources on parsing the file. There are upper limits for fields that I parse, but it can still be unreasonable. I can imagine a conforming font that's explicitly written to exist at those limits. These issues also exist for `rusttype`, but those libraries don't do their parsing upfront, and may trigger slow behavior later into their lifecycles.
